apiVersion: v1
kind: Pod
metadata:
  name: multicontainer
  namespace: roboshop
  labels:
    name: multicontainer-pod
    project: roboshop
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
    - name: redis
      image: redis:latest
      ports:
        - containerPort: 6379